using System;

namespace JAVA
{
  class Program
  {
    static void Main(string[] args)
   {
     Console.WriteLine("Hit Enter To Play");
     Console.ReadLine();
   Console.WriteLine("What Numbered Month Di 9/11 Happen");
   Console.ReadLine();
   
   if(answer == "9"){
     Console.WriteLine("Correct");
   }
   
   else(){
     Console.WriteLine("Incorrect");
   }
   
   Console.WriteLine("What Is 69 * 420 Is");
   Console.ReadLine();
    if(answer == "28980"){
      Console.WriteLine("Correct");
    }
    
    else(){
      Console.WriteLine("Incorrect, It Was 22980");
    }
    
  Console.WriteLine("Who");
  Console.ReadLine();
  
  Console.WriteLine("ASKED ");
  Console.WriteLine("HAR HAR HAR HAR HAR");
  Console.ReadLine();
  `
  Console.WriteLine("Why Did The Chicken Cross The Road");
  Console.ReadLine();
  if(answer == "Suiside"){
    Console.WriteLine("CORRECT")
  }
  else(){
    Console.WriteLine("")
  }
}
